name: .venv
channels:
  - conda-forge
dependencies:
  - python=3.8.13
  - appnope==0.1.3
  - astroid==2.11.6
  - asttokens==2.0.5
  - backcall==0.2.0
  - black==22.3.0
  - catboost==1.0.6
  - click==8.1.3
  - cycler==0.11.0
  - debugpy==1.6.0
  - decorator==5.1.1
  - dill==0.3.5.1
  - entrypoints==0.4
  - executing==0.8.3
  - flake8==4.0.1
  - fonttools==4.33.3
  #- graphviz==0.20
  - ipykernel==6.15.0
  - ipython==8.4.0
  - isort==5.10.1
  - jedi==0.18.1
  - joblib==1.1.0
  #- jupyter-client==7.3.4
  #- jupyter-core==4.10.0
  - kiwisolver==1.4.3
  - lazy-object-proxy==1.7.1
  - matplotlib==3.5.2
  - matplotlib-inline==0.1.3
  - mccabe==0.6.1
  #- mypy-extensions==0.4.3
  - nest-asyncio==1.5.5
  - numpy==1.22.4
  - packaging==21.3
  - pandas==1.4.2
  - parso==0.8.3
  - pathspec==0.9.0
  - pexpect==4.8.0
  - pickleshare==0.7.5
  - Pillow==9.1.1
  - platformdirs==2.5.2
  - plotly==5.8.2
  - prompt-toolkit==3.0.29
  - psutil==5.9.1
  - ptyprocess==0.7.0
 # - pure-eval==0.2.2
  - pycodestyle==2.8.0
  - pyflakes==2.4.0
  - Pygments==2.12.0
  - pylint==2.14.3
  - pyparsing==3.0.9
  - python-dateutil==2.8.2
  - pytz==2022.1
  - PyYAML==6.0
  - pyzmq==23.2.0
  - scikit-learn==1.1.1
  - scipy==1.8.1
  - six==1.16.0
 # - stack-data==0.3.0
  - tenacity==8.0.1
  - threadpoolctl==3.1.0
  - tomli==2.0.1
  - tomlkit==0.11.0
  - tornado==6.1
  - traitlets==5.3.0
  - wcwidth==0.2.5
  - wrapt==1.14.1
  - typer==0.5.0
  - azure-storage-blob==12.13.0
  - bandit==1.7.4
  - pre-commit==2.18.1
  - pytest==7.1.2
 # - pytest-azurepipelines==1.0.3
  - pytest-cov==3.0.0
  - pip:  
    - azureml-mlflow
    - mltable
    - azureml-interpret
    - interpret-community
    - azure-ai-ml
    - azureml-core
    - lightgbm
    - pytest-azurepipelines